"""
Professional Daily Swing Signal Ranker
=======================================

Ranks valid signals generated by the deterministic
daily swing strategy.

Strategy:
    EMA 5 / 13 / 26
    MACD 12 / 26 / 9
    RSI 14
    LONG RSI > 60
    SHORT RSI < 40

Maximum score = 100

Components:
    EMA Trend Alignment       20
    MACD Confirmation         15
    RSI Quality               15
    Volume Confirmation       15
    Price Extension           10
    Signal Freshness          10
    Risk / Reward              15
                              ---
                              100
"""

from __future__ import annotations

import pandas as pd


INPUT_FILE = "output/daily_signals.csv"
OUTPUT_FILE = "output/ranked_daily_signals.csv"


# ============================================================
# HELPERS
# ============================================================


def safe_float(value, default=0.0) -> float:
    """Safely convert a value to float."""

    try:
        number = float(value)

        if pd.isna(number):
            return default

        return number

    except (TypeError, ValueError):
        return default


def clamp(
    value: float,
    minimum: float,
    maximum: float,
) -> float:
    """Keep a value inside the requested range."""

    return max(
        minimum,
        min(value, maximum),
    )


# ============================================================
# EMA SCORE
# ============================================================


def score_ema(
    row: pd.Series,
    signal: str,
) -> float:
    """
    EMA trend score.

    Maximum: 20

    LONG:
        EMA5 > EMA13 > EMA26

    SHORT:
        EMA5 < EMA13 < EMA26

    The score measures the strength of the separation
    between the three EMAs.
    """

    ema5 = safe_float(
        row.get("ema_5")
    )

    ema13 = safe_float(
        row.get("ema_13")
    )

    ema26 = safe_float(
        row.get("ema_26")
    )

    if ema5 <= 0 or ema13 <= 0 or ema26 <= 0:
        return 0.0

    if signal == "LONG":

        if not (
            ema5 > ema13
            and ema13 > ema26
        ):
            return 0.0

        fast_gap = (
            (ema5 - ema13)
            / ema13
            * 100
        )

        slow_gap = (
            (ema13 - ema26)
            / ema26
            * 100
        )

    elif signal == "SHORT":

        if not (
            ema5 < ema13
            and ema13 < ema26
        ):
            return 0.0

        fast_gap = (
            (ema13 - ema5)
            / ema13
            * 100
        )

        slow_gap = (
            (ema26 - ema13)
            / ema26
            * 100
        )

    else:
        return 0.0

    combined_gap = (
        fast_gap
        + slow_gap
    )

    # Around 2% combined separation reaches
    # the maximum score.
    score = combined_gap * 10.0

    return round(
        clamp(
            score,
            0.0,
            20.0,
        ),
        2,
    )


# ============================================================
# MACD SCORE
# ============================================================


def score_macd(
    row: pd.Series,
    signal: str,
) -> float:
    """
    MACD confirmation score.

    Maximum: 15

    Important:
        MACD values cannot be compared directly between
        stocks because their magnitude depends on the
        stock's price and volatility.

    Therefore we measure:

        abs(MACD - Signal)
        -------------------
        abs(Signal)

    This gives a relative MACD separation.

    The deterministic strategy already requires the
    actual MACD crossover. The ranker therefore measures
    how strongly MACD remains separated after the crossover.
    """

    macd = safe_float(
        row.get("macd")
    )

    macd_signal = safe_float(
        row.get("macd_signal")
    )

    histogram = (
        macd
        - macd_signal
    )

    # Direction must agree with signal.
    if signal == "LONG":

        if histogram <= 0:
            return 0.0

    elif signal == "SHORT":

        if histogram >= 0:
            return 0.0

    else:
        return 0.0

    # Use signal-line magnitude as the normalizing scale.
    #
    # When signal line is very close to zero, using it directly
    # would create an unstable ratio. In that case use MACD
    # magnitude instead.

    scale = max(
        abs(macd_signal),
        abs(macd) * 0.25,
        0.01,
    )

    relative_strength = (
        abs(histogram)
        / scale
    )

    # Score according to relative separation.
    if relative_strength >= 1.00:
        score = 15.0

    elif relative_strength >= 0.75:
        score = 14.0

    elif relative_strength >= 0.50:
        score = 13.0

    elif relative_strength >= 0.35:
        score = 12.0

    elif relative_strength >= 0.25:
        score = 10.0

    elif relative_strength >= 0.15:
        score = 8.0

    elif relative_strength >= 0.10:
        score = 6.0

    elif relative_strength >= 0.05:
        score = 4.0

    else:
        score = 2.0

    return round(
        score,
        2,
    )


# ============================================================
# RSI SCORE
# ============================================================


def score_rsi(
    row: pd.Series,
    signal: str,
) -> float:
    """
    RSI quality score.

    Maximum: 15

    LONG:
        RSI > 60

    SHORT:
        RSI < 40

    We prefer RSI that has crossed the threshold
    without becoming excessively extended.
    """

    rsi = safe_float(
        row.get("rsi")
    )

    if signal == "LONG":

        if rsi <= 60:
            return 0.0

        if rsi <= 64:
            score = 15.0

        elif rsi <= 68:
            score = 14.0

        elif rsi <= 72:
            score = 12.0

        elif rsi <= 76:
            score = 8.0

        else:
            score = 4.0

    elif signal == "SHORT":

        if rsi >= 40:
            return 0.0

        if rsi >= 36:
            score = 15.0

        elif rsi >= 32:
            score = 14.0

        elif rsi >= 28:
            score = 12.0

        elif rsi >= 24:
            score = 8.0

        else:
            score = 4.0

    else:
        return 0.0

    return round(
        score,
        2,
    )


# ============================================================
# VOLUME SCORE
# ============================================================


def score_volume(
    row: pd.Series,
) -> float:
    """
    Volume confirmation score.

    Maximum: 15
    """

    volume_ratio = safe_float(
        row.get("volume_ratio")
    )

    if volume_ratio >= 5.0:
        score = 15.0

    elif volume_ratio >= 3.0:
        score = 13.0

    elif volume_ratio >= 2.0:
        score = 11.0

    elif volume_ratio >= 1.5:
        score = 9.0

    elif volume_ratio >= 1.0:
        score = 7.0

    elif volume_ratio >= 0.75:
        score = 4.0

    elif volume_ratio >= 0.50:
        score = 2.0

    else:
        score = 0.0

    return round(
        score,
        2,
    )


# ============================================================
# PRICE EXTENSION SCORE
# ============================================================


def score_extension(
    row: pd.Series,
) -> float:
    """
    Price extension score.

    Maximum: 10

    Measures distance between current entry price
    and EMA5.

    Smaller extension = fresher setup.
    """

    entry = safe_float(
        row.get("entry")
    )

    ema5 = safe_float(
        row.get("ema_5")
    )

    if entry <= 0 or ema5 <= 0:
        return 0.0

    extension = (
        abs(entry - ema5)
        / ema5
        * 100
    )

    if extension <= 1.0:
        score = 10.0

    elif extension <= 2.0:
        score = 9.0

    elif extension <= 3.0:
        score = 8.0

    elif extension <= 4.0:
        score = 6.0

    elif extension <= 5.0:
        score = 4.0

    elif extension <= 7.0:
        score = 2.0

    else:
        score = 0.0

    return round(
        score,
        2,
    )


# ============================================================
# FRESHNESS SCORE
# ============================================================


def score_freshness(
    row: pd.Series,
) -> float:
    """
    Signal freshness score.

    Maximum: 10.

    The scanner currently records signal_date but does not
    record a separate latest_data_date. Therefore a valid
    signal is treated as fresh unless a latest_date column
    exists.
    """

    signal_date = pd.to_datetime(
        row.get("signal_date"),
        errors="coerce",
    )

    if pd.isna(signal_date):
        return 0.0

    if "latest_date" not in row.index:
        return 10.0

    latest_date = pd.to_datetime(
        row.get("latest_date"),
        errors="coerce",
    )

    if pd.isna(latest_date):
        return 10.0

    days_old = max(
        0,
        (
            latest_date.normalize()
            - signal_date.normalize()
        ).days,
    )

    if days_old == 0:
        score = 10.0

    elif days_old == 1:
        score = 8.0

    elif days_old == 2:
        score = 5.0

    elif days_old == 3:
        score = 2.0

    else:
        score = 0.0

    return round(
        score,
        2,
    )


# ============================================================
# RISK / REWARD SCORE
# ============================================================


def score_risk_reward(
    row: pd.Series,
) -> float:
    """
    Risk/reward score.

    Maximum: 15.
    """

    rr = safe_float(
        row.get("risk_reward")
    )

    if rr >= 4.0:
        score = 15.0

    elif rr >= 3.5:
        score = 14.0

    elif rr >= 3.0:
        score = 13.0

    elif rr >= 2.5:
        score = 11.0

    elif rr >= 2.0:
        score = 9.0

    elif rr >= 1.5:
        score = 5.0

    else:
        score = 0.0

    return round(
        score,
        2,
    )


# ============================================================
# COMPLETE SCORE
# ============================================================


def calculate_score(
    row: pd.Series,
) -> dict:
    """Calculate all score components."""

    signal = str(
        row.get(
            "signal",
            "",
        )
    ).upper()

    ema_score = score_ema(
        row,
        signal,
    )

    macd_score = score_macd(
        row,
        signal,
    )

    rsi_score = score_rsi(
        row,
        signal,
    )

    volume_score = score_volume(
        row,
    )

    extension_score = score_extension(
        row,
    )

    freshness_score = score_freshness(
        row,
    )

    rr_score = score_risk_reward(
        row,
    )

    total_score = (
        ema_score
        + macd_score
        + rsi_score
        + volume_score
        + extension_score
        + freshness_score
        + rr_score
    )

    return {
        "ema_score": round(
            ema_score,
            2,
        ),
        "macd_score": round(
            macd_score,
            2,
        ),
        "rsi_score": round(
            rsi_score,
            2,
        ),
        "volume_score": round(
            volume_score,
            2,
        ),
        "extension_score": round(
            extension_score,
            2,
        ),
        "freshness_score": round(
            freshness_score,
            2,
        ),
        "rr_score": round(
            rr_score,
            2,
        ),
        "quality_score": round(
            total_score,
            2,
        ),
    }


# ============================================================
# QUALITY LABEL
# ============================================================


def quality_label(
    score: float,
) -> str:
    """Convert score into quality category."""

    if score >= 80:
        return "STRONG"

    if score >= 65:
        return "GOOD"

    if score >= 50:
        return "MODERATE"

    return "WEAK"


# ============================================================
# RANK SIGNALS
# ============================================================


def rank_signals(
    df: pd.DataFrame,
) -> pd.DataFrame:
    """Rank all valid strategy signals."""

    required_columns = {
        "scan_status",
        "signal",
        "symbol",
        "exchange",
        "signal_date",
        "entry",
        "risk_reward",
        "rsi",
        "ema_5",
        "ema_13",
        "ema_26",
        "macd",
        "macd_signal",
        "volume_ratio",
    }

    missing = (
        required_columns
        - set(df.columns)
    )

    if missing:
        raise ValueError(
            "Missing required columns: "
            f"{sorted(missing)}"
        )

    # Only valid strategy signals.
    signals = df[
        df["scan_status"]
        .astype(str)
        .str.upper()
        == "SIGNAL"
    ].copy()

    if signals.empty:
        return signals

    numeric_columns = [
        "entry",
        "risk_reward",
        "rsi",
        "ema_5",
        "ema_13",
        "ema_26",
        "macd",
        "macd_signal",
        "volume_ratio",
    ]

    for column in numeric_columns:

        signals[column] = pd.to_numeric(
            signals[column],
            errors="coerce",
        )

    score_rows = []

    for _, row in signals.iterrows():

        score_rows.append(
            calculate_score(row)
        )

    score_df = pd.DataFrame(
        score_rows
    )

    signals = signals.reset_index(
        drop=True
    )

    signals = pd.concat(
        [
            signals,
            score_df,
        ],
        axis=1,
    )

    signals["quality"] = (
        signals["quality_score"]
        .apply(
            quality_label
        )
    )

    # Rank primarily by total score.
    # Remaining fields provide deterministic tie-breaking.
    signals = signals.sort_values(
        by=[
            "quality_score",
            "macd_score",
            "ema_score",
            "rsi_score",
            "volume_score",
            "extension_score",
        ],
        ascending=[
            False,
            False,
            False,
            False,
            False,
            False,
        ],
    ).reset_index(
        drop=True
    )

    signals["rank"] = range(
        1,
        len(signals) + 1,
    )

    return signals


# ============================================================
# PRINT RESULTS
# ============================================================


def print_results(
    ranked: pd.DataFrame,
) -> None:
    """Print ranking results."""

    print()
    print("=" * 110)
    print(
        "PROFESSIONAL DAILY SWING SIGNAL RANKING"
    )
    print("=" * 110)

    if ranked.empty:

        print()
        print("NO VALID SIGNALS")
        return

    display_columns = [
        "rank",
        "exchange",
        "symbol",
        "signal",
        "signal_date",
        "entry",
        "stop_loss",
        "target",
        "risk_reward",
        "rsi",
        "volume_ratio",
        "quality_score",
        "quality",
    ]

    available_columns = [
        column
        for column in display_columns
        if column in ranked.columns
    ]

    print(
        ranked[
            available_columns
        ].to_string(
            index=False
        )
    )

    print()
    print("=" * 70)
    print("TOP LONG SIGNALS")
    print("=" * 70)

    longs = ranked[
        ranked["signal"]
        .astype(str)
        .str.upper()
        == "LONG"
    ]

    if longs.empty:

        print("None")

    else:

        for _, row in longs.head(5).iterrows():

            print(
                f"{row['rank']}. "
                f"{row['symbol']} | "
                f"{row['quality_score']}/100 | "
                f"{row['quality']}"
            )

    print()
    print("=" * 70)
    print("TOP SHORT SIGNALS")
    print("=" * 70)

    shorts = ranked[
        ranked["signal"]
        .astype(str)
        .str.upper()
        == "SHORT"
    ]

    if shorts.empty:

        print("None")

    else:

        for _, row in shorts.head(5).iterrows():

            print(
                f"{row['rank']}. "
                f"{row['symbol']} | "
                f"{row['quality_score']}/100 | "
                f"{row['quality']}"
            )

    print()
    print("=" * 70)
    print("SCORE BREAKDOWN")
    print("=" * 70)

    for _, row in ranked.iterrows():

        print(
            f"{row['symbol']:<15} "
            f"{row['signal']:<6} "
            f"TOTAL={row['quality_score']:>5.2f} | "
            f"EMA={row['ema_score']:>5.2f} | "
            f"MACD={row['macd_score']:>5.2f} | "
            f"RSI={row['rsi_score']:>5.2f} | "
            f"VOL={row['volume_score']:>5.2f} | "
            f"EXT={row['extension_score']:>5.2f} | "
            f"FRESH={row['freshness_score']:>5.2f} | "
            f"RR={row['rr_score']:>5.2f}"
        )


# ============================================================
# MAIN
# ============================================================


def main() -> None:
    """Run the ranking engine."""

    print("=" * 70)
    print("DAILY SWING SIGNAL RANKER")
    print("=" * 70)

    print()
    print(
        f"Loading: {INPUT_FILE}"
    )

    df = pd.read_csv(
        INPUT_FILE
    )

    print(
        f"Rows loaded: {len(df)}"
    )

    ranked = rank_signals(
        df
    )

    print_results(
        ranked
    )

    ranked.to_csv(
        OUTPUT_FILE,
        index=False,
    )

    print()
    print("=" * 70)
    print("RANKING COMPLETE")
    print("=" * 70)

    print()
    print(
        f"Valid signals: {len(ranked)}"
    )

    print(
        f"Saved to: {OUTPUT_FILE}"
    )


if __name__ == "__main__":
    main()